language: php
php:
  - '7.1'
services:
  - mysql
before_script:
  - mysql -u root --password="" < tests/config/travis_start.sql
  - echo "<?php return ['host'=>'127.0.0.1','user'=>'travis','db'=>'tests'];" > tests/config/pdo_mysql_connection.php
  - composer install
script:
  - bin/runtests
  - bin/coverage tests/clover.xml 80
after_success:
  - bash <(curl -s https://codecov.io/bash)
