branches:
  only:
    - master
language: php
php:
  - '7.1'
  - '7.2'
services:
  - mysql
  - mongodb
  - postgresql
before_script:
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - mysql -u root --password="" < tests/config/travis_init_mysql.sql
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -d travis_ci_test -U postgres -a -f tests/config/travis_init_pgsql.sql
  - echo "<?php return ['host'=>'127.0.0.1','user'=>'travis','db'=>'h2l_tests'];" > tests/config/pdo_mysql_connection.php
  - echo "<?php return ['host'=>'127.0.0.1','user'=>'travis','db'=>'test'];" > tests/config/mongo_connection.php
  - echo "<?php return ['scheme'=>'pgsql','host'=>'127.0.0.1','user'=>'postgres','pass'=>'','db'=>'travis_ci_test'];" > tests/config/pdo_pgsql_connection.php
  - composer install
script:
  - bin/runtests
  - php bin/coverage tests/clover.xml 95
after_success:
  - bash <(curl -s https://codecov.io/bash)
