DROP DATABASE IF EXISTS `h2l_tests`;
CREATE DATABASE `h2l_tests`;
USE `h2l_tests`;
CREATE TABLE `tests` ( `id` INT UNSIGNED NOT NULL AUTO_INCREMENT , `name` VARCHAR(256) NOT NULL DEFAULT 'A name' , `age` INT UNSIGNED NOT NULL DEFAULT '69' , PRIMARY KEY (`id`)) ENGINE = InnoDB;
