name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: GitHub Actions
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        tools: composer, phpstan, phpunit

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run PHPStan
      run: ./vendor/bin/phpstan.phar --version
    #   run: ./vendor/bin/phpstan.phar analyse -c phpstan.neon --no-interaction --no-progress

    # - name: Run Test Suite
    # run: ./bin/runtests --coverage-clover tests/clover.xml

    - name: Run A Test
      run: ./bin/runtests --filter=ModelTest